spring:
  application:
    name: JPAEntityManager
  datasource:
    url: jdbc:postgresql://localhost:5432/book_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update